from infrastructure.repositories_impl.canteens_repository_impl import CanteensRepositoryImpl
from infrastructure.repositories_impl.main_dishes_repository_impl import MainDishesRepositoryImpl
from infrastructure.repositories_impl.side_dishes_repository_impl import SideDishesRepositoryImpl

canteens_repository = CanteensRepositoryImpl()
main_dishes_repository = MainDishesRepositoryImpl()
side_dishes_repository = SideDishesRepositoryImpl()

