from application.services.set_all_schedulers_service import SetAllSchedulersService
from infrastructure.config.scheduler_interfaces_config import scheduler_interface

set_all_scheduler_service = SetAllSchedulersService(scheduler_interface=scheduler_interface)